'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { app } = require('./helpers');

test('first run: splash, form, folder created, result overlay, floor', async (t) => {
  const a = await app(t, { seed: false });
  if (!a) return;
  const { page } = a;
  await a.goto('/');
  await page.waitForSelector('#firstrun h2');
  assert.match(await page.textContent('#firstrun h2'), /How AAR works/);
  assert.match(await page.textContent('#firstrun'), /Administrative Assistant Robots/);
  await page.click('#begin');
  await page.waitForSelector('#setup');
  assert.match(await page.textContent('#firstrun h2'), /Create the Chief of Staff/);
  assert.match(await page.textContent('#pathnote'), /created if it does not exist|does not exist yet/);
  await page.fill('input[name=name]', 'Alfred');
  await page.click('.swatch[data-accent="#2e7d6b"]');
  await page.click('.cast label:nth-child(4)');
  await page.click('#setup button.primary');
  await page.waitForSelector('#overlay .firstrun h2');
  const note = await page.textContent('#overlay .firstrun');
  assert.match(note, /Alfred has an office/);
  assert.match(note, /did not exist, so it was created/);
  assert.match(note, /git init/);
  assert.ok(fs.existsSync(path.join(a.staffDir, 'Chief of Staff', 'aa.conf')));
  const conf = fs.readFileSync(path.join(a.staffDir, 'Chief of Staff', 'aa.conf'), 'utf8');
  assert.match(conf, /name=Alfred - Chief of Staff/);
  assert.match(conf, /accent=#2e7d6b/);
  assert.match(conf, /avatar=cast-11\.png/);
  const settings = JSON.parse(fs.readFileSync(a.env.AAR_CONFIG, 'utf8'));
  assert.equal(settings.staffDir, a.staffDir);
  await page.click('#tofloor');
  await page.waitForSelector('.person[data-id="Chief of Staff"]');
  assert.match(await page.textContent('.person .plate .n'), /Alfred/);
  assert.match(await page.textContent('.person .plate .r'), /Chief of Staff/);
  await page.click('#helplink');
  await page.waitForSelector('#overlay .firstrun');
  assert.match(await page.textContent('#overlay'), /never modifies or deletes/);
});

test('change the staff folder from the header', async (t) => {
  const a = await app(t);
  if (!a) return;
  const { page } = a;
  await a.goto('/');
  await page.waitForSelector('.person');
  assert.equal(await page.locator('.person').count(), 5);
  await page.click('#staffdir');
  await page.waitForSelector('#repoint');
  const other = path.join(path.dirname(a.staffDir), 'other-staff');
  await page.fill('#repoint input[name=staffDir]', other);
  await page.click('#repoint button.primary');
  await page.waitForSelector('#firstrun h2');
  assert.equal(JSON.parse(fs.readFileSync(a.env.AAR_CONFIG, 'utf8')).staffDir, other);
  assert.ok(!fs.existsSync(other), 'pointing at a folder does not create it');
});
